# Generated by Django 6.0.5 on 2026-05-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timersetting',
            name='break_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='timersetting',
            name='total_cycles',
            field=models.IntegerField(default=4),
        ),
    ]
