# Generated by Django 6.0.5 on 2026-06-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timersetting',
            name='sound_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
