# Generated by Django 6.0.5 on 2026-06-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_timersetting_sound_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_quick_task',
            field=models.BooleanField(default=False),
        ),
    ]
