# Generated by Django 6.0.5 on 2026-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_description_task_is_quick_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Study', 'Study'), ('Health', 'Health'), ('Shopping', 'Shopping'), ('Professional', 'Professional'), ('Personal', 'Personal'), ('Finance', 'Finance'), ('Household', 'Household')], max_length=20, null=True),
        ),
    ]
