# Generated by Django 6.0.5 on 2026-06-25 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_dailyactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together={('user', 'date')},
        ),
    ]
