# Generated by Django 6.0.5 on 2026-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='had_activity',
            field=models.BooleanField(default=False),
        ),
    ]
